# Generated by Django 5.2.7 on 2025-10-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_lesson_studentprogress'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
