# Generated by Django 3.2.25 on 2026-01-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_options_course_level_exam_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('CC', 'Contrôle Continu'), ('SN', 'Session Normale'), ('SR', 'Session Rattrapage')], default='SN', max_length=2),
        ),
    ]
