# Generated by Django 3.2.25 on 2026-02-07 11:18

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
