# Generated by Django 5.2.11 on 2026-03-08 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20260210_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='target_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], help_text='Level this question is targeted at', null=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
